- name: install nginx
  yum:
    name: nginx
    state: latest
- name: copy nginx conf
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'default.conf.j2', dest: '/etc/nginx/conf.d/default.conf' }
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
  notify: restart nginx
- name: create dir
  file:
    path: '{{ html_root }}'
    owner: nginx
    group: nginx
    state: directory
- name: copy html
  copy:
    src: index.html
    dest: '{{ html_root }}'
- name: Start service nginx, if not started
  service:
    name: nginx
    state: started
