- name: install the latest version of lsyncd
  yum:
    name: lsyncd
    state: installed
- name: cp lsyncd.conf
  copy:
    src: lsyncd.conf
    dest: /etc/lsyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart lsyncd
- name: Start service lsyncd , if not started
  service:
    name: lsyncd
    state: started
    enabled: yes
