- name: install the latest version of rsync
  yum:
    name: rsync
    state: latest
- name: example copying rsync.password
  copy:
    src: rsync.password
    dest: /etc/rsync.password
    owner: root
    group: root
    mode: 0600
- name: Add nginx Yum Repository
  yum_repository:
    name: nginx-stable
    description: nginx-stable Repository
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
